# --- !Ups

create table "USERS" ("ID" SERIAL PRIMARY KEY ,
  "FIRSTNAME" VARCHAR(100) NOT NULL ,
  "LASTNAME" VARCHAR(100) NOT NULL,
  "EMAIL" VARCHAR(250) NOT NULL UNIQUE,
  "PROVIDER_ID" VARCHAR(250) NOT NULL ,
  "PROVIDER_KEY" VARCHAR(250) NOT NULL,
  UNIQUE ("PROVIDER_ID","PROVIDER_KEY"));

create table "ROLES" (
  "ID" SERIAL PRIMARY KEY ,
  "USER_ID" INTEGER REFERENCES "USERS",
  "ROLE" VARCHAR(30),
  UNIQUE ("ID","USER_ID","ROLE")
);

create table "PASSWORDINFO" (
  "ID" SERIAL PRIMARY KEY ,
  "HASHER" VARCHAR NOT NULL ,
  "PASSWORD" VARCHAR NOT NULL,
  "SALT" VARCHAR,
  "USER_ID" INTEGER REFERENCES "USERS"
);

create INDEX loginInfo_index ON "USERS" ("PROVIDER_ID","PROVIDER_KEY") ;

# --- !Downs
drop INDEX loginInfo_index;
drop TABLE "PASSWORDINFO";
drop TABLE "ROLES";
drop table "USERS";